data:
  test_size : 0.2
  random_state : 42

model:
  degress : 2 #polynomial degree x^2
  weight_init_scale : 0.01 # weight initialized multiplier

training:
  learning_rate : 0.00001
  epochs : 2000
  log_interval : 100 #print log function at evey 100 time interval